const E={branch:document.getElementById('branch'),notes:document.getElementById('notes'),start:document.getElementById('start'),sessionText:document.getElementById('sessionText'),searchForm:document.getElementById('searchForm'),search:document.getElementById('search'),results:document.getElementById('results'),counted:document.getElementById('counted'),complete:document.getElementById('complete'),searchMsg:document.getElementById('searchMsg'),actionMsg:document.getElementById('actionMsg')};let session=null;const items=new Map();

(async()=>{if(!await scAuth())return;const b=await scBranches();E.branch.innerHTML=b.map(x=>`<option value="${x.id}">${scEsc(x.code)} — ${scEsc(x.name)}</option>`).join('')})();

E.start.onclick=async()=>{const{data,error}=await supabaseClient.rpc('create_stock_count_session',{p_branch_id:E.branch.value,p_notes:E.notes.value||null});if(error)return scMsg(E.actionMsg,error.message,'error');session=data;items.clear();render();E.sessionText.textContent=`รอบ ${data.count_no}`;scMsg(E.actionMsg,'เริ่มรอบตรวจนับแล้ว','ok')};

E.searchForm.onsubmit=async e=>{e.preventDefault();if(!session)return scMsg(E.searchMsg,'กรุณาเริ่มรอบตรวจนับก่อน','error');const q=E.search.value.trim().replace(/[%_,()]/g,'');const{data,error}=await supabaseClient.from('branch_inventory_list').select('*').eq('branch_id',E.branch.value).or(`product_name.ilike.%${q}%,product_code.ilike.%${q}%,barcode.eq.${q}`).limit(20);if(error)return scMsg(E.searchMsg,error.message,'error');E.results.innerHTML='';(data||[]).forEach(x=>{const d=document.createElement('div');d.className='item';d.innerHTML=`<div><b>${scEsc(x.product_name)}</b><small>${scEsc(x.product_code)} • ระบบ ${scNum(x.quantity)}</small></div>`;const input=document.createElement('input');input.className='qty';input.type='number';input.min='0';input.step='.001';input.placeholder='ยอดนับจริง';const b=document.createElement('button');b.className='btn primary';b.textContent='บันทึก';b.onclick=async()=>{const counted=Number(input.value);if(Number.isNaN(counted)||counted<0)return scMsg(E.searchMsg,'กรอกยอดนับจริงให้ถูกต้อง','error');const{data,error}=await supabaseClient.rpc('save_stock_count_item',{p_session_id:session.id,p_product_id:x.product_id,p_counted_quantity:counted,p_note:null});if(error)return scMsg(E.searchMsg,error.message,'error');items.set(x.product_id,{...x,system_quantity:data.system_quantity,counted_quantity:data.counted_quantity,variance:data.variance});render();scMsg(E.searchMsg,'บันทึกยอดนับแล้ว','ok')};const box=document.createElement('div');box.className='row';box.append(input,b);d.append(box);E.results.appendChild(d)});scMsg(E.searchMsg,`พบ ${(data||[]).length} รายการ`)};

function render(){E.counted.innerHTML='';for(const x of items.values()){const cls=x.variance>0?'variance-plus':x.variance<0?'variance-minus':'variance-zero';const sign=x.variance>0?'+':'';const d=document.createElement('div');d.className='item';d.innerHTML=`<div><b>${scEsc(x.product_name)}</b><small>ระบบ ${scNum(x.system_quantity)} • นับจริง ${scNum(x.counted_quantity)}</small></div><div class="${cls}">${sign}${scNum(x.variance)}</div>`;E.counted.appendChild(d)}}

E.complete.onclick=async()=>{if(!session)return scMsg(E.actionMsg,'ยังไม่มีรอบตรวจนับ','error');if(!items.size)return scMsg(E.actionMsg,'ยังไม่มีรายการที่นับ','error');if(!confirm('ยืนยันปรับยอดสต๊อกตามยอดนับจริง?'))return;const{data,error}=await supabaseClient.rpc('complete_stock_count_session',{p_session_id:session.id});if(error)return scMsg(E.actionMsg,error.message,'error');scMsg(E.actionMsg,`ปิดรอบ ${data.count_no} เรียบร้อย`,'ok');session=null;items.clear();render();E.sessionText.textContent='ยังไม่ได้เริ่มรอบ'};
