-- TKN Final v5.20.0 Sort Pack QR
create table if not exists public.sorting_lots (id uuid primary key default gen_random_uuid(), lot_code text unique not null, tracking_number text not null, source text, status text not null default 'OPEN', note text, created_by uuid default auth.uid(), created_at timestamptz default now(), closed_at timestamptz);
create table if not exists public.sorting_lot_items (id uuid primary key default gen_random_uuid(), lot_id uuid references public.sorting_lots(id) on delete cascade, source_item_id text, product_id uuid references public.products(id), source_sku text, sku text, product_name text not null, category text, quantity numeric not null default 1, unit_cost numeric not null default 0, cost_code text, status text not null default 'PENDING', box_code text, created_at timestamptz default now());
create table if not exists public.marketplace_sorting_source_items (id uuid primary key default gen_random_uuid(), source text, tracking_number text, order_number text, source_sku text, sku text, product_name text, category text, quantity numeric default 1, unit_cost numeric default 0, product_id uuid references public.products(id), raw_data jsonb default '{}'::jsonb, created_at timestamptz default now());
create index if not exists idx_sort_source_tracking on public.marketplace_sorting_source_items(tracking_number);create index if not exists idx_sort_lot_tracking on public.sorting_lots(tracking_number);
alter table public.sorting_lots enable row level security;alter table public.sorting_lot_items enable row level security;alter table public.marketplace_sorting_source_items enable row level security;
do $$ begin create policy "authenticated sorting lots" on public.sorting_lots for all to authenticated using(true) with check(true); exception when duplicate_object then null; end $$;
do $$ begin create policy "authenticated sorting items" on public.sorting_lot_items for all to authenticated using(true) with check(true); exception when duplicate_object then null; end $$;
do $$ begin create policy "authenticated sorting source" on public.marketplace_sorting_source_items for all to authenticated using(true) with check(true); exception when duplicate_object then null; end $$;
